[environments.local]
kind = "local"
env = {"CUSTOM_PARAM" = "target_local_env_value"}

[environments.ssh_raspberrypi]
kind = "ssh"
host = "raspberrypi"
user = "pi"
env = {"CUSTOM_PARAM" = "target_remote_env_value"}

# [io]
# print_output = false

[task_template_loaders.dir_toml]
# enabled = false
path = "%sys.cwd%/examples/task_templates/toml"
